# Generated by Django 5.2.3 on 2025-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_color_alter_product_image_product_colors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="api/static/images/categories"
            ),
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
