# Generated by Django 5.2.3 on 2025-06-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_product_subcategory_category_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="image",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="image",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="imageUrl",
        ),
        migrations.RenameField(
            model_name="store",
            old_name="logo",
            new_name="logoUrl",
        ),
    ]
