# Generated by Django 5.2.3 on 2025-06-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_image_banner_imageurl_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="logoUrl",
            new_name="imageUrl",
        ),
    ]
