# Generated by Django 5.2.3 on 2025-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_store_imageurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="imageUrl",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="unique_category_name_case_insensitive",
                violation_error_message="Category name must be unique (case-insensitive)",
            ),
        ),
    ]
