# Generated by Django 5.2.3 on 2025-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("vendor", "Vendor")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
